module.exports = [
    { name: "tacker",
      description: "a simple web bundler" },
    { name: "docker-nativescript",
      description: "a dockerized version of nativescript toolchain" },
    { name: "dotfiles",
      description: "personal configuration files and scripts" },
    { name: "reverseqr",
      description: "qr codes working in both directions" },
    { name: "sleeb",
      description: "an experimental input method" },
    { name: "timetracker",
      description: "suckless timetracking" },
    { name: "url-tetris",
      description: "tetris inside the browser address bar" },
    { name: "terrain-generator",
      description: "digital terrain generation and animation" },
    { name: "remark-slides",
      description: "personal distribution of remarkjs" },
    { name: "ramajs",
      description: "web browser automation from your browser console" },
    { name: "brainfuck-2048",
      description: "brainfuck implementation of the well-known 2048 game" },
    { name: "tongong.net",
      description: "personal website" },
];
